[package]
name = "async-recurr"
version = "0.1.0"
authors = ["Kazik24 <kazik24official@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
futures = "0.3.5"

[dependencies]
